INSERT INTO "user" ("name", "email", "email_verified", "image", "role", "link_name", "time_zone") VALUES
('John Doe', 'john.doe@example.com', TRUE, 'https://randomuser.me/api/portraits/men/42.jpg', 'advisor', 'john-doe', 'EST'),
('Jane Smith', 'jane.smith@example.com', TRUE, 'https://randomuser.me/api/portraits/women/17.jpg', 'advisor', 'jane-smith', 'PST'),
('Peter Jones', 'peter.jones@example.com', TRUE, 'https://randomuser.me/api/portraits/men/88.jpg', 'advisor', 'peter-jones', 'GMT'),
('Sarah Brown', 'sarah.brown@example.com', TRUE, 'https://randomuser.me/api/portraits/women/63.jpg', 'advisor', 'sarah-brown', 'JST'),
('Michael Davis', 'michael.davis@example.com', TRUE, 'https://randomuser.me/api/portraits/men/5.jpg', 'advisor', 'michael-davis', 'AEST'),
('Emily White', 'emily.white@example.com', TRUE, 'https://randomuser.me/api/portraits/women/91.jpg', 'advisor', 'emily-white', 'CST'),
('David Green', 'david.green@example.com', TRUE, 'https://randomuser.me/api/portraits/men/29.jpg', 'advisor', 'david-green', 'CET'),
('Olivia Hall', 'olivia.hall@example.com', TRUE, 'https://randomuser.me/api/portraits/women/34.jpg', 'advisor', 'olivia-hall', 'MST'),
('Daniel Clark', 'daniel.clark@example.com', TRUE, 'https://randomuser.me/api/portraits/men/76.jpg', 'advisor', 'daniel-clark', 'SAST'),
('Sophia Lewis', 'sophia.lewis@example.com', TRUE, 'https://randomuser.me/api/portraits/women/50.jpg', 'advisor', 'sophia-lewis', 'CST'),
('James Scott', 'james.scott@example.com', TRUE, 'https://randomuser.me/api/portraits/men/11.jpg', 'advisor', 'james-scott', 'EST'),
('Isabella King', 'isabella.king@example.com', TRUE, 'https://randomuser.me/api/portraits/women/22.jpg', 'advisor', 'isabella-king', 'CET'),
('William Wright', 'william.wright@example.com', TRUE, 'https://randomuser.me/api/portraits/men/95.jpg', 'advisor', 'william-wright', 'CST'),
('Mia Taylor', 'mia.taylor@example.com', TRUE, 'https://randomuser.me/api/portraits/women/8.jpg', 'advisor', 'mia-taylor', 'GST'),
('Alexander Moore', 'alexander.moore@example.com', TRUE, 'https://randomuser.me/api/portraits/men/39.jpg', 'advisor', 'alexander-moore', 'AEST'),
('Charlotte Hill', 'charlotte.hill@example.com', TRUE, 'https://randomuser.me/api/portraits/women/71.jpg', 'advisor', 'charlotte-hill', 'PST'),
('Benjamin Turner', 'benjamin.turner@example.com', TRUE, 'https://randomuser.me/api/portraits/men/60.jpg', 'advisor', 'benjamin-turner', 'CET'),
('Amelia Adams', 'amelia.adams@example.com', TRUE, 'https://randomuser.me/api/portraits/women/45.jpg', 'advisor', 'amelia-adams', 'BRT'),
('Ethan Baker', 'ethan.baker@example.com', TRUE, 'https://randomuser.me/api/portraits/men/2.jpg', 'advisor', 'ethan-baker', 'SGT'),
('Harper Nelson', 'harper.nelson@example.com', TRUE, 'https://randomuser.me/api/portraits/women/99.jpg', 'advisor', 'harper-nelson', 'EET');

INSERT INTO "advisor" ("title", "bio", "city", "state", "country", "user_id") VALUES
('Senior Business Consultant', 'Experienced in strategic planning and market analysis for small to medium-sized businesses.', 'New York', 'New York', 'United States', (SELECT id FROM "user" WHERE "email" = 'john.doe@example.com')),
('Healthcare Policy Advisor', 'Specializing in healthcare regulations and patient advocacy, helping navigate complex systems.', 'Los Angeles', 'California', 'United States', (SELECT id FROM "user" WHERE "email" = 'jane.smith@example.com')),
('Educational Technology Specialist', 'Passionate about integrating technology into modern learning environments and curriculum development.', 'London', 'England', 'United Kingdom', (SELECT id FROM "user" WHERE "email" = 'peter.jones@example.com')),
('Financial Planning Expert', 'Dedicated to helping individuals achieve financial independence through personalized investment strategies.', 'Tokyo', 'Tokyo', 'Japan', (SELECT id FROM "user" WHERE "email" = 'sarah.brown@example.com')),
('Certified Fitness Coach', 'Guiding clients towards healthier lifestyles with personalized exercise plans and nutritional advice.', 'Sydney', 'New South Wales', 'Australia', (SELECT id FROM "user" WHERE "email" = 'michael.davis@example.com')),
('Software Architecture Advisor', 'Providing expert guidance on scalable software solutions and system design for tech startups.', 'Chicago', 'Illinois', 'United States', (SELECT id FROM "user" WHERE "email" = 'emily.white@example.com')),
('Creative Arts Consultant', 'Assisting artists with career development, portfolio reviews, and marketing strategies in the art world.', 'Berlin', 'Berlin', 'Germany', (SELECT id FROM "user" WHERE "email" = 'david.green@example.com')),
('Life and Leadership Coach', 'Empowering individuals to unlock their full potential and achieve personal and professional growth.', 'Denver', 'Colorado', 'United States', (SELECT id FROM "user" WHERE "email" = 'olivia.hall@example.com')),
('Real Estate Investment Advisor', 'Advising on property acquisitions, market trends, and maximizing returns on real estate investments.', 'Johannesburg', 'Gauteng', 'South Africa', (SELECT id FROM "user" WHERE "email" = 'daniel.clark@example.com')),
('Environmental Science Researcher', 'Focused on sustainable practices and environmental impact assessments for various industries.', 'Shanghai', 'Shanghai', 'China', (SELECT id FROM "user" WHERE "email" = 'sophia.lewis@example.com')),
('Startup Business Mentor', 'Helping new ventures with business model canvas development and fundraising strategies.', 'Toronto', 'Ontario', 'Canada', (SELECT id FROM "user" WHERE "email" = 'james.scott@example.com')),
('Public Health Consultant', 'Expert in community health programs and disease prevention strategies.', 'Paris', 'Ile-de-France', 'France', (SELECT id FROM "user" WHERE "email" = 'isabella.king@example.com')),
('Academic Success Coach', 'Assisting students with study techniques, time management, and career planning.', 'Mexico City', 'Mexico City', 'Mexico', (SELECT id FROM "user" WHERE "email" = 'william.wright@example.com')),
('Wealth Management Advisor', 'Providing tailored financial advice for high-net-worth individuals and families.', 'Dubai', 'Dubai', 'United Arab Emirates', (SELECT id FROM "user" WHERE "email" = 'mia.taylor@example.com')),
('Sports Performance Specialist', 'Optimizing athletic performance through strength training, nutrition, and mental conditioning.', 'Brisbane', 'Queensland', 'Australia', (SELECT id FROM "user" WHERE "email" = 'alexander.moore@example.com')),
('UX/UI Design Consultant', 'Crafting user-centered designs and intuitive interfaces for digital products.', 'Vancouver', 'British Columbia', 'Canada', (SELECT id FROM "user" WHERE "email" = 'charlotte.hill@example.com')),
('Art Therapy Practitioner', 'Utilizing creative expression to promote emotional well-being and personal insight.', 'Rome', 'Lazio', 'Italy', (SELECT id FROM "user" WHERE "email" = 'benjamin.turner@example.com')),
('Mindfulness and Wellness Coach', 'Guiding individuals in developing mindfulness practices for stress reduction and improved well-being.', 'Sao Paulo', 'Sao Paulo', 'Brazil', (SELECT id FROM "user" WHERE "email" = 'amelia.adams@example.com')),
('Cybersecurity Strategist', 'Developing robust security frameworks and protecting digital assets for organizations.', 'Singapore', 'Central Region', 'Singapore', (SELECT id FROM "user" WHERE "email" = 'ethan.baker@example.com')),
('Astrophysics Communicator', 'Making complex scientific concepts accessible and engaging for a broad audience.', 'Cairo', 'Cairo Governorate', 'Egypt', (SELECT id FROM "user" WHERE "email" = 'harper.nelson@example.com'));

INSERT INTO "advisor_category" ("advisor_id", "category_id", "is_primary") VALUES
(1, 1, TRUE),
(1, 4, FALSE),
(2, 2, TRUE),
(2, 8, FALSE),
(3, 3, TRUE),
(3, 6, FALSE),
(4, 4, TRUE),
(4, 1, FALSE),
(5, 5, TRUE),
(5, 8, FALSE),
(6, 6, TRUE),
(6, 1, FALSE),
(7, 7, TRUE),
(7, 8, FALSE),
(8, 8, TRUE),
(8, 1, FALSE),
(9, 9, TRUE),
(9, 4, FALSE),
(10, 10, TRUE),
(10, 1, FALSE),
(11, 1, TRUE),
(11, 4, FALSE),
(12, 2, TRUE),
(12, 8, FALSE),
(13, 3, TRUE),
(13, 8, FALSE),
(14, 4, TRUE),
(14, 1, FALSE),
(15, 5, TRUE),
(15, 8, FALSE),
(16, 6, TRUE),
(16, 7, FALSE),
(17, 7, TRUE),
(17, 8, FALSE),
(18, 8, TRUE),
(18, 2, FALSE),
(19, 6, TRUE),
(19, 1, FALSE),
(20, 10, TRUE),
(20, 3, FALSE);
